---
language: ruby
cache: bundler
bundler_args: --without system_tests development
script: "bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 4.2" 
notifications:
  email: false
  hipchat:
    rooms:
      - secure: iSPprJS+t7TDKKHdvr2pRcMe51IlYvjOz+BzC2Ih3R9gkLFHjqLgCemGAi6Ab1URjRuhe8rb0RK1gDb0DHlrWMp0PVQTJyKH+67saK3eWZC59fKW1eJtjHgiMNYzmmi+Yq0zOhUnLILU/D77KvImn5T0bWp2L6OW0XXxoJOTEj4=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
  on_success: always
  on_failure: always
